### ISSUE TITLE
Use 'javax.annotation:jsr250-api:1.0'

### ISSUE THREAD

**Issue by rgrigoryev** [mgrzechocinski/dagger2-example#1]
Using `provided 'org.glassfish:javax.annotation:10.0-b28'` at  https://github.com/mgrzechocinski/dagger2-example/blob/master/app/build.gradle#L45  was very confusing for me. I suggest to use `provided 'javax.annotation:jsr250-api:1.0'` instead with some comment.

**Comment by mgrzechocinski** [comment]
Frankly, didn't know that `jsr250-api` jar exists in cenral repo. The only artifact I found, containing `@Generated` required by Dagger2 was `jorg.glassfish:javax.annotation:10.0-b28`. 

Goot to know that. Thanks for this hint. I've just updated `build.gradle` in the [latest commit](https://github.com/mgrzechocinski/dagger2-example/commit/57020b0a1969f092a5b09440d44b89730f25de3b)
