### ISSUE TITLE
Where is DaggerD2EComponent?

### ISSUE THREAD

**Issue by derekcsm** [mgrzechocinski/dagger2-example#8]
I've looked seemingly everywhere, and can't find `DaggerD2EComponent` referenced as an import here: https://github.com/mgrzechocinski/dagger2-example/blob/master/app/src/main/java/net/grzechocinski/android/dagger2example/D2EBaseApplication.java#L9

**Comment by midnight-wonderer** [comment]
The class will be generated when you build the project.
Check this file:
app/build/generated/source/apt/debug/net/grzechocinski/android/dagger2example/internal/di/DaggerD2EComponent.java

**Comment by derekcsm** [comment]
Ah yup I didn't build, that was my issue :+1:
